version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bostad_tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Auto-run init.sql
    networks:
      - app_network

  php:
    build:
      context: php_backend
    container_name: php_server
    restart: always
    volumes:
      - ./php_backend:/var/www/html
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=bostad_tracker
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpass
      - API_KEY=supersecretapikey
    depends_on:
      - mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: