<?php
$kommuner = [
    "Botkyrka",
    "Danderyd",
    "Haninge",
    "Huddinge",
    "Järfälla",
    "Lidingö",
    "Nacka",
    "Norrtälje",
    "Nykvarn",
    "Nynäshamn",
    "Salem",
    "Sigtuna",
    "Sollentuna",
    "Solna",
    "Stockholm",
    "Strängnäs",
    "Sundbyberg"
];

$stadsdelar = [
    "Alby",
    "Norsborg",
    "Slagsta strand",
    "Tullinge",
    "Tumba",
    "Mörby Centrum",
    "Mörbylund",
    "Brandbergen",
    "Handen",
    "Jordbro",
    "Vega",
    "Flemingsberg",
    "Huddinge Centrum",
    "Källbrink",
    "Segeltorp",
    "Sjödalen-Fullersta",
    "Skogås",
    "Trångsund",
    "Vårby",
    "Barkarby",
    "Barkarbystaden",
    "Jakobsbergs Centrum",
    "Säby Gård",
    "Söderdalen",
    "Söderhöjden",
    "Veddesta",
    "Baggeby",
    "Bodal",
    "Dalénum",
    "Käppala",
    "Larsberg",
    "Skärsätra",
    "Sticklinge",
    "Alphyddan",
    "Björknäs",
    "Eknäs",
    "Ektorp",
    "Finntorp",
    "Fisksätra",
    "Nacka Centrum",
    "Nacka Strand",
    "Orminge",
    "Tollare",
    "Älta",
    "Nynäshamn Centrum",
    "Ösmo",
    "Arenberga",
    "Märsta Centrum",
    "Norrbacka",
    "Sigtuna",
    "Steninge",
    "Steningehöjden",
    "Tingvalla",
    "Valsta",
    "Östra Steninge",
    "Edsberg",
    "Häggvik",
    "Rotebro",
    "Rotsunda",
    "Silverdal",
    "Skälby",
    "Tureberg",
    "Väsjön",
    "Bergshamra",
    "Frösunda",
    "Hagalund",
    "Huvudsta",
    "Råsunda",
    "Skytteholm",
    "Stocksundstorp",
    "Ulriksdal",
    "Abrahamsberg",
    "Akalla",
    "Aspudden",
    "Bagarmossen",
    "Bandhagen",
    "Beckomberga",
    "Björkhagen",
    "Blackeberg",
    "Bredäng",
    "Bromsten",
    "Enskede Gård",
    "Enskededalen",
    "Fagersjö",
    "Farsta",
    "Farsta Strand",
    "Fredhäll",
    "Fruängen",
    "Gamla Enskede",
    "Gamla Stan",
    "Grimsta",
    "Gröndal",
    "Gubbängen",
    "Hagsätra",
    "Hammarbyhöjden",
    "Hjorthagen",
    "Husby",
    "Hägersten",
    "Hägerstensåsen",
    "Hässelby Gård",
    "Hässelby Strand",
    "Högdalen",
    "Hökarängen",
    "Johanneshov",
    "Kista",
    "Kristineberg",
    "Kungsholmen",
    "Kärrtorp",
    "Ladugårdsgärdet",
    "Larsboda",
    "Liljeholmen",
    "Lilla Essingen",
    "Långbro",
    "Marieberg",
    "Mariehäll",
    "Midsommarkransen",
    "Mälarhöjden",
    "Nockebyhov",
    "Norra Djurgården",
    "Norra Ängby",
    "Norrmalm",
    "Riksby",
    "Rinkeby",
    "Råcksta",
    "Rågsved",
    "Skarpnäcks Gård",
    "Skärholmen",
    "Sköndal",
    "Solberga",
    "Solhem",
    "Stadshagen",
    "Stureby",
    "Svedmyra",
    "Sätra",
    "Södermalm",
    "Södra Hammarbyhamnen",
    "Tallkrogen",
    "Tensta",
    "Traneberg",
    "Ulvsunda",
    "Ulvsunda Industriområde",
    "Vasastaden",
    "Vinsta",
    "Vårberg",
    "Vällingby",
    "Västberga",
    "Västertorp",
    "Åkeshov",
    "Åkeslund",
    "Årsta",
    "Älvsjö",
    "Örby",
    "Örby Slott",
    "Östberga",
    "Östermalm",
    "Hallonbergen",
    "Lilla Alby",
    "Rissne",
    "Sundbyberg Centrum"
];
?>
