"""Mocked data for tests"""
from bostad_scraper.apartments import Apartment, Coordinate

MOCKED_APARTMENTS = [
    Apartment(
        id=1,
        city_area='södermalm',
        address='götgatan 1',
        kommun='stockholm',
        floor=3,
        num_rooms=2,
        size_sqm=50,
        rent=10000,
        coordinate=Coordinate(lat=59.314, lon=18.072),
        url='https://example.com/1',
        has_balcony=True,
        has_elevator=True,
        new_production=False,
        youth=False,
        student=False,
        senior=False,
        short_lease=False,
        regular=True,
        apartment_type='hyresrätt'
    ),
    Apartment(
        id=2,
        city_area='kungsholmen',
        address='st eriksgatan 10',
        kommun='stockholm',
        floor=5,
        num_rooms=3,
        size_sqm=70,
        rent=15000,
        coordinate=Coordinate(lat=59.333, lon=18.030),
        url='https://example.com/2',
        has_balcony=False,
        has_elevator=True,
        new_production=True,
        youth=False,
        student=False,
        senior=False,
        short_lease=True,
        regular=True,
        apartment_type='hyresrätt'
    ),
    Apartment(
        id=3,
        city_area='vasastan',
        address='odengatan 22',
        kommun='stockholm',
        floor=1,
        num_rooms=1,
        size_sqm=30,
        rent=7000,
        coordinate=Coordinate(lat=59.345, lon=18.055),
        url='https://example.com/3',
        has_balcony=True,
        has_elevator=False,
        new_production=False,
        youth=True,
        student=False,
        senior=False,
        short_lease=False,
        regular=True,
        apartment_type='hyresrätt'
    ),
]